// M0.5 landing rebuild: nav, data-driven subject showcase, sections, CTAs, no overflow.
const { test, expect } = require('@playwright/test');

test('landing has nav, dynamic counts, and a data-driven subject showcase', async ({ page }) => {
  const errors = [];
  page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));

  await page.goto('/');
  await page.waitForFunction(
    () => window.SOKRAT_CATALOG && document.querySelectorAll('#landingSubjects .landing-subject-card').length > 0
  );

  // BROJ i VITRINA imaju različit doseg, i to je namjerno (Leon, 2026-08-09):
  //  • broj      = CIJELA platforma kroz sve programe (17 EN + 5 HR = 22)
  //  • vitrina   = samo primarni program; HR predmeti se dohvaćaju kroz Browse
  // Prije je i broj bio vezan na primarni program, pa je landing pisao 17 iako ih ima 22.
  const counts = await page.evaluate(() => {
    const seen = {}; let total = 0;
    (SOKRAT_CATALOG.faculties || []).forEach((f) => (f.programs || []).forEach((p) => {
      SokratCatalog.subjectsOf(p.id).forEach((s) => { if (s && s.id && !seen[s.id]) { seen[s.id] = true; total++; } });
    }));
    return { total: total, primary: SokratCatalog.subjectsOf('hospitality-management').length };
  });

  // Regresijska brana: da netko vrati broj na primarni program, `total` i `primary` bi se
  // poklopili i tvrdnja ispod bi prošla lažno. Ovo traži da razlika STVARNO postoji.
  expect(counts.total, 'katalog nema više programa — test bi postao bezvrijedan')
    .toBeGreaterThan(counts.primary);

  // Nav present
  await expect(page.locator('.landing-nav')).toBeVisible();

  // Dynamic subject count reflects the WHOLE catalog
  const metaText = await page.$eval('[data-meta="subjectCount"]', (el) => el.textContent.trim());
  expect(metaText).toBe(String(counts.total));

  // Dynamic question count comes from autogenerated data/landing-stats.js (not a hardcoded "400+").
  const qStat = await page.evaluate(() => window.SOKRAT_STATS && window.SOKRAT_STATS.questionCount);
  expect(typeof qStat).toBe('number');
  expect(qStat).toBeGreaterThan(0);
  const qText = await page.$eval('[data-meta="questionCount"]', (el) => el.textContent.trim());
  expect(qText).toBe(qStat.toLocaleString('en-US') + '+');

  // Vitrina ostaje na primarnom programu (namjerno uža od brojke gore)
  const showcase = await page.$$eval('#landingSubjects .landing-subject-card', (e) => e.length);
  expect(showcase).toBe(counts.primary);

  // Sections present
  expect(await page.$$eval('#how .how-step', (e) => e.length)).toBe(3);
  expect(await page.$$eval('#modes .mode-card', (e) => e.length)).toBe(5);
  await expect(page.locator('.landing-footer .footer-cols')).toBeVisible();

  // No horizontal overflow on the (now long) landing page
  const vw = page.viewportSize().width;
  const docScrollW = await page.evaluate(() => document.documentElement.scrollWidth);
  expect(docScrollW).toBeLessThanOrEqual(vw + 1);

  expect(errors).toEqual([]);
});

test('landing CTAs and showcase navigate correctly', async ({ page }) => {
  const errors = [];
  page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));

  await page.goto('/');
  await page.waitForFunction(
    () => window.enterBrowse && document.querySelectorAll('#landingSubjects .landing-subject-card').length > 0
  );

  // Showcase card → lessons page for that subject
  await page.click('#landingSubjects .landing-subject-card[data-landing-subject="te2"]');
  await page.waitForSelector('#lessons-page.active', { timeout: 5000 });
  const title = (await page.textContent('#currentSubjectTitle')) || '';
  expect(title).toContain('Tourism Economics');

  // Back to landing, then a "Start studying" trigger → browse drill-down
  await page.evaluate(() => window.navigateTo('landing'));
  await page.waitForSelector('#landing-page.active');
  await page.click('.landing-nav .start-trigger');
  await page.waitForSelector('#browse-page.active', { timeout: 5000 });
  await page.waitForSelector('.browse-card[data-browse="faculty"]');

  expect(errors).toEqual([]);
});

// Regression: hero badge must clear the fixed top nav (it was tucked UNDER the bar
// because the hero offset was a hardcoded magic number < real nav height on mobile).
test('hero badge clears the fixed top nav (no overlap)', async ({ page }) => {
  await page.goto('/');
  await page.waitForSelector('.landing-nav');
  await page.waitForSelector('.hero-badge');

  const { navBottom, badgeTop } = await page.evaluate(() => {
    const nav = document.querySelector('.landing-nav').getBoundingClientRect();
    const badge = document.querySelector('.hero-badge').getBoundingClientRect();
    return { navBottom: nav.bottom, badgeTop: badge.top };
  });

  // Badge must start at or below the bottom edge of the fixed nav (1px tolerance).
  expect(badgeTop).toBeGreaterThanOrEqual(navBottom - 1);
});
