/* eslint-disable no-console */
// ===== Assemble subject — korak 4 generatora predmeta =====
// Usage:
//   node scripts/assemble-subject.js <subjectId> [--name "Naziv"] [--short XYZ]
//        [--icon fa-book] [--color "#3b82f6"] [--year 1] [--sem 1] [--desc "..."]
//
// Čita tmp/<subjectId>/draft.json (iz generate-subject.js) i piše:
//   data/<subjectId>/midterm-1.js   → window.<var>M1  (+ module.exports)
//   data/<subjectId>/midterm-2.js   → window.<var>M2
//   data/<subjectId>/final.js       → window.<var>Final = Object.assign({}, M1, M2)   (ZADNJI)
//
// SIGURNOST: tijela datoteka serijaliziraju se preko JSON.stringify → JSON je validan
// JS objekt-literal, pa su svi navodnici/backslashevi/KaTeX delimiteri ispravno escapani
// (NEMA ručnog escapea = nema grešaka). examPractice se NE generira (ručno/Opus kasnije).
//
// Catalog NE dira automatski (najosjetljivije) — ISPISUJE gotov unos za zalijepiti + checklist.
// Nakon toga: paste u data/catalog.js → bump CONTENT_VERSION → validate:content → verify → Playwright.

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');

const camel = (s) => s.toLowerCase().split(/[^a-z0-9]+/i).filter(Boolean)
  .map((w, i) => (i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1))).join('');

function arg(name, def) { const i = process.argv.indexOf(name); return i >= 0 ? process.argv[i + 1] : def; }

function dataFile(varName, dataObj, headerName) {
  return `// ===== ${headerName} — GENERATED by scripts/assemble-subject.js =====\n`
    + `// ⚠ Auto-generirano iz materijala. PREGLEDAJ protiv predavanja prije objave.\n`
    + `// Izmjena sadržaja: uredi ovdje pa bumpaj CONTENT_VERSION (js/content-loader.js).\n\n`
    + `const ${varName} = ${JSON.stringify(dataObj, null, 2)};\n\n`
    + `if (typeof window !== 'undefined') { window.${varName} = ${varName}; }\n`
    + `if (typeof module !== 'undefined' && module.exports) { module.exports = ${varName}; }\n`;
}

function finalFile(varBase, headerName) {
  const M1 = varBase + 'M1', M2 = varBase + 'M2', F = varBase + 'Final';
  return `// ===== ${headerName} — FINAL (hybrid) — GENERATED by scripts/assemble-subject.js =====\n`
    + `// Mora se učitati ZADNJI. Spaja oba kolokvija; examPractice dodaj ručno kasnije ako želiš.\n\n`
    + `const ${F} = Object.assign(\n`
    + `  {},\n`
    + `  (typeof window !== 'undefined' && window.${M1}) ? window.${M1} : {},\n`
    + `  (typeof window !== 'undefined' && window.${M2}) ? window.${M2} : {}\n`
    + `);\n\n`
    + `if (typeof window !== 'undefined') { window.${F} = ${F}; }\n`
    + `if (typeof module !== 'undefined' && module.exports) { module.exports = ${F}; }\n`;
}

function selfCheck(scripts, vars) {
  const sandbox = { window: {}, console, Math, Object, Array, JSON, String, Number, Boolean, Date };
  vm.createContext(sandbox);
  for (const rel of scripts) vm.runInContext(fs.readFileSync(path.join(ROOT, rel), 'utf8'), sandbox, { filename: rel });
  const out = [];
  for (const [lesson, v] of Object.entries(vars)) {
    const obj = sandbox.window[v];
    const n = obj && typeof obj === 'object' ? Object.keys(obj).length : 0;
    if (!n && lesson === 'final') throw new Error(`self-check: ${v} (final) prazan — nema sadržaja ni u jednom kolokviju`);
    if (!n) out.push(`⚠ ${lesson} → ${v}: PRAZAN (nema tema u draftu za taj kolokvij)`);
    else out.push(`${lesson} → ${v}: ${n} kategorija`);
  }
  return out;
}

function main() {
  const subjectId = process.argv[2];
  if (!subjectId || subjectId.startsWith('--')) { console.error('Usage: node scripts/assemble-subject.js <subjectId> [--name ..][--short ..][--icon ..][--color ..][--year N][--sem N][--desc ..]'); process.exit(1); }

  const draftFile = path.join(ROOT, 'tmp', subjectId, 'draft.json');
  if (!fs.existsSync(draftFile)) { console.error('Nema ' + path.relative(ROOT, draftFile) + ' — pokreni generate-subject.js prvo.'); process.exit(1); }
  const draft = JSON.parse(fs.readFileSync(draftFile, 'utf8'));

  const m1 = draft.lessons['first-midterm'] || {};
  const m2 = draft.lessons['second-midterm'] || {};
  if (!Object.keys(m1).length && !Object.keys(m2).length) { console.error('Draft nema kategorija ni u jednom kolokviju.'); process.exit(1); }

  const varBase = camel(subjectId);
  const name = arg('--name', subjectId);
  const shortName = arg('--short', subjectId.slice(0, 5).toUpperCase());
  const icon = arg('--icon', 'fa-book-open');
  const color = arg('--color', '#3b82f6');
  const year = Number(arg('--year', '1'));
  const sem = Number(arg('--sem', '1'));
  const desc = arg('--desc', name + ' — generated study content.');

  const outDir = path.join(ROOT, 'data', subjectId);
  fs.mkdirSync(outDir, { recursive: true });

  fs.writeFileSync(path.join(outDir, 'midterm-1.js'), dataFile(varBase + 'M1', m1, name + ' — K1'));
  fs.writeFileSync(path.join(outDir, 'midterm-2.js'), dataFile(varBase + 'M2', m2, name + ' — K2'));
  fs.writeFileSync(path.join(outDir, 'final.js'), finalFile(varBase, name));

  const scripts = [`data/${subjectId}/midterm-1.js`, `data/${subjectId}/midterm-2.js`, `data/${subjectId}/final.js`];
  const vars = { 'first-midterm': varBase + 'M1', 'second-midterm': varBase + 'M2', 'final': varBase + 'Final' };

  console.log('\nNapisane datoteke:');
  for (const s of scripts) console.log('  ✓ ' + s);
  console.log('\nSelf-check (vm):');
  for (const line of selfCheck(scripts, vars)) console.log('  ✓ ' + line);

  // --- Catalog unos (za zalijepiti u data/catalog.js -> subjects[]) ---
  const entry = {
    id: subjectId,
    programId: 'hospitality-management',
    year, semester: sem,
    name, shortName, icon, color,
    iconGradient: [color, color],
    description: desc,
    storageKey: subjectId + '-progress',
    features: { blindMap: false, exercises: false },
    lessons: [
      { id: 'first-midterm', name: 'First Midterm', description: 'First midterm topics' },
      { id: 'second-midterm', name: 'Second Midterm', description: 'Second midterm topics' },
      { id: 'final', name: 'Final Exam', description: 'All topics (both midterms)' }
    ],
    content: { scripts, resolve: vars }
  };

  console.log('\n================ CATALOG UNOS (zalijepi u data/catalog.js → subjects[]) ================');
  // Skini navodnike SAMO s valjanih JS identifikatora; hyphen-ključevi (npr. "first-midterm")
  // MORAJU ostati citirani (inače je crtica oduzimanje → syntax error).
  console.log(JSON.stringify(entry, null, 2).replace(/"([a-zA-Z_$][a-zA-Z0-9_$]*)":/g, '$1:') + ',');
  console.log('\n================ SLJEDEĆI KORACI (ručno, uz provjeru) ================');
  console.log('  1. Zalijepi gornji unos u data/catalog.js (subjects[]). Final.js MORA biti zadnji u scripts.');
  console.log('  2. Bumpaj CONTENT_VERSION u js/content-loader.js (+ ?v= u index.html ako mijenjaš i js/css).');
  console.log('  3. npm run validate:content ' + subjectId + '   (sadržajni zaštitar)');
  console.log('  4. npm run verify   (catalog integritet)');
  console.log('  5. npm run test:responsive   (Playwright render)');
  console.log('  6. Opus/ti: činjenični spot-check protiv predavanja.');
}

main();
